In [1]:
import pandas as pd
import sys
sys.path.append('..')

In [2]:
from src.core.trainer import Trainer
from src.model.linear_regression  import LinearRegressionModel
from src.model.ridge_regression   import RidgeRegressionModel
from src.model.lasso_regression   import LassoRegressionModel
from src.model.huber_regression   import HuberRegressionModel

In [3]:

# Load LinearPreprocessor data (cần scale cho regression)
train = pd.read_csv('../data/processed/linear/train.csv')
test  = pd.read_csv('../data/processed/linear/test.csv')
display(train.head())
display(test.head())

,elevation_m,drainage_density_km_per_km2,storm_drain_proximity_m,historical_rainfall_intensity_mm_hr,return_period_years,is_very_low_elev,rain_x_return,soil_group,land_use_Commercial,land_use_Green,...,rainfall_source_Unknown,dem_source_Copernicus_EEA-10_v5,dem_source_Copernicus_GLO-30_v2023,dem_source_Copernicus_GLO-90_v2022,dem_source_SRTM_1arc,dem_source_SRTM_3arc,risk_class,risk_class_encoded,latitude,longitude
0,0.064497,0.575000,0.420451,-0.837699,0.000000,0.0,-0.199116,-0.5,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,Low,1,38.853632,-77.017289
1,0.091598,-0.567857,-0.349135,0.296904,-0.459186,0.0,-0.110141,0.0,0.0,1.0,...,1.0,0.0,0.0,0.0,1.0,0.0,Low,1,21.065060,105.831464
2,-0.285603,0.000000,1.265114,0.868131,-0.459186,0.0,0.090570,-0.5,1.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,Low,1,22.633800,113.957179
3,-0.770107,0.021429,-0.526973,0.094981,-1.079361,0.0,-0.643264,-0.5,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,Medium,2,41.393959,2.143102
4,-0.545320,1.167857,0.240823,-0.647833,1.185333,0.0,0.833661,-0.5,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,Low,1,31.350399,121.515148

,elevation_m,drainage_density_km_per_km2,storm_drain_proximity_m,historical_rainfall_intensity_mm_hr,return_period_years,is_very_low_elev,rain_x_return,soil_group,land_use_Commercial,land_use_Green,...,rainfall_source_Unknown,dem_source_Copernicus_EEA-10_v5,dem_source_Copernicus_GLO-30_v2023,dem_source_Copernicus_GLO-90_v2022,dem_source_SRTM_1arc,dem_source_SRTM_3arc,risk_class,risk_class_encoded,latitude,longitude
0,-0.237228,0.060714,-0.165362,-0.577831,1.185333,0.0,0.853695,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,Low,1,-33.972494,151.193279
1,0.000000,0.000000,0.891073,1.504583,-1.079361,0.0,-0.107797,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,High,0,-22.938550,-43.299984
2,0.000000,0.342857,0.078738,-1.577798,-0.459186,0.0,-0.858390,0.5,1.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,Low,1,35.709772,139.856430
3,-0.829300,0.000000,0.000000,-0.185534,-0.459186,0.0,-0.288402,-1.0,0.0,0.0,...,1.0,0.0,0.0,1.0,0.0,0.0,Medium,2,38.813354,-77.080088
4,-0.524288,1.507143,-0.738143,1.299589,0.000000,0.0,0.524347,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,High,0,19.090451,72.879029

In [4]:
trainer1 = Trainer(model=LinearRegressionModel())
trainer1.tune(train)
trainer1.evaluate_test(test)

[Trainer] Tuning LinearRegressionModel...
  CV=10, n_iter=50, scorer=F2-macro
  Class distribution: {0: 316, 1: 1595, 2: 459}
  SMOTE k_neighbors : 5
Fitting 10 folds for each of 45 candidates, totalling 450 fits

c:\Users\LENOVO\Downloads\khu lap trinh\machine_learning\ML_project\.venv\Lib\site-packages\sklearn\model_selection\_search.py:318: UserWarning: The total space of parameters 45 is smaller than n_iter=50. Running 45 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(

  Fitting LinearRegressionModel...
    Iter 100/1000, loss=0.378508
    Threshold optimized: t1=0.7143, t2=1.3214
    Train F2-macro: 0.6040

  Best params     : {'tol': 1e-06, 'max_iter': 1000, 'learning_rate': 0.01}
  Best CV F2-macro: 0.5499
  Train F2-macro  : 0.5607
  ✅ Overfit gap=0.0109 — ổn

[Test] F2-macro    : 0.5269
[Test] F1-weighted : 0.5645

{'f2_macro': 0.5268651819039416, 'f1_weighted': 0.5644862062419228}

In [8]:
import pickle

In [11]:
with open("../config/LinearRegression.pkl", "wb") as f:
    pickle.dump(trainer1.model, f)

In [5]:
trainer2 = Trainer(model=RidgeRegressionModel())
trainer2.tune(train)
trainer2.evaluate_test(test)

[Trainer] Tuning RidgeRegressionModel...
  CV=10, n_iter=50, scorer=F2-macro
  Class distribution: {0: 316, 1: 1595, 2: 459}
  SMOTE k_neighbors : 5
Fitting 10 folds for each of 50 candidates, totalling 500 fits
  Fitting RidgeRegressionModel...
    Iter 100/1000, loss=0.386813
    Iter 200/1000, loss=0.383015
    Iter 300/1000, loss=0.386118
    Iter 400/1000, loss=0.390836
    Iter 500/1000, loss=0.382096
    Iter 600/1000, loss=0.381175
    Iter 700/1000, loss=0.379680
    Iter 800/1000, loss=0.379309
    Iter 900/1000, loss=0.380937
    Iter 1000/1000, loss=0.380276
    Threshold optimized: t1=0.7460, t2=1.3015
    Train F2-macro: 0.6058

  Best params     : {'max_iter': 1000, 'learning_rate': 0.05, 'alpha': 0.001}
  Best CV F2-macro: 0.5412
  Train F2-macro  : 0.5542
  ✅ Overfit gap=0.0131 — ổn

[Test] F2-macro    : 0.5091
[Test] F1-weighted : 0.5414

{'f2_macro': 0.5091040856338066, 'f1_weighted': 0.5414269797184066}

In [6]:
trainer3 = Trainer(model=LassoRegressionModel())
trainer3.tune(train)
trainer3.evaluate_test(test)

[Trainer] Tuning LassoRegressionModel...
  CV=10, n_iter=50, scorer=F2-macro
  Class distribution: {0: 316, 1: 1595, 2: 459}
  SMOTE k_neighbors : 5
Fitting 10 folds for each of 50 candidates, totalling 500 fits
  Fitting LassoRegressionModel...
    Iter 100/500, loss=0.378131
    Iter 200/500, loss=0.373348
    Iter 300/500, loss=0.374902
    Iter 400/500, loss=0.382031
    Iter 500/500, loss=0.371632
    Threshold optimized: t1=0.6885, t2=1.3006
    Train F2-macro: 0.6141

  Best params     : {'max_iter': 500, 'learning_rate': 0.05, 'alpha': 0.0001}
  Best CV F2-macro: 0.5456
  Train F2-macro  : 0.5664
  ✅ Overfit gap=0.0207 — ổn

[Test] F2-macro    : 0.5381
[Test] F1-weighted : 0.5611

{'f2_macro': 0.5380508645568597, 'f1_weighted': 0.561112277544292}

In [7]:
trainer4 = Trainer(model = HuberRegressionModel())
trainer4.tune(train)
trainer4.evaluate_test(test)

[Trainer] Tuning HuberRegressionModel...
  CV=10, n_iter=50, scorer=F2-macro
  Class distribution: {0: 316, 1: 1595, 2: 459}
  SMOTE k_neighbors : 5
Fitting 10 folds for each of 50 candidates, totalling 500 fits
  Fitting HuberRegressionModel...
    Iter 100/500, loss=0.185247
    Threshold optimized: t1=0.6942, t2=1.3548
    Train F2-macro: 0.6138

  Best params     : {'max_iter': 500, 'learning_rate': 0.05, 'delta': 1.0}
  Best CV F2-macro: 0.5484
  Train F2-macro  : 0.5663
  ✅ Overfit gap=0.0179 — ổn

[Test] F2-macro    : 0.5363
[Test] F1-weighted : 0.5844

{'f2_macro': 0.5363398214150753, 'f1_weighted': 0.5843756079765002}

In [21]:
modelt = trainer4.model
print(modelt.best_params)

{'max_iter': 500, 'learning_rate': 0.05, 'delta': 1.0}

In [22]:
print(modelt.weights)

None